[package]
name = "dining_philosophers"
version = "0.1.0"
authors = ["HKatoo <h.kato-7129@keio.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
